config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'welcome/index'

  root 'welcome#index'

  post '/' => 'sessions#create'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

   resources :users
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

    get "posts/search" => "posts#search", as: 'search'
    get "posts/random" => "posts#random", as: "random"

    resources :posts do
      resources :comments, only: [:index, :create, :destroy], shallow:true
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch

  pg_search_scope :search_by_posts, :against => :caption,
    :using =>  {:tsearch => {:prefix => true}
   }


  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :comments, dependent: :destroy

  def is_belongs_to? user
        #Post.find_by(user_id: user.id, id: id)
        self.user == user
    end
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, :format => { :with => /\w+[@]\w+[.]\w{1}\w+/}, uniqueness: true, :presence => true
  validates :password, presence: true

  has_secure_password

  has_many :posts
  has_many :comments

  has_many :authentications, dependent: :destroy

  def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     first_name: auth_hash["info"]["first_name"],
     last_name: auth_hash["info"]["last_name"],
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10),
   )
   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end

 def full_name
   "#{self.first_name} #{self.last_name}"
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception
    helper_method :current_user, :signed_in?, :sign_out

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def signed_in?
      !current_user.nil?
    end

    def sign_in(user)
      session[:user_id] = user.id
    end

    def sign_out
      session[:user_id] = nil
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = @post.comments.include(:user)
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
       @post = @comment.post
       respond_to do |format|
       format.html
       format.js
      end
    else
        flash[:alert] = "Something went wrong."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
      @post = @comment.post
      if @comment.destroy
        respond_to do |format|   
        format.html
        format.js
        end
      else
        flash[:alert] = "Something went wrong."
      end
  end

  private
    def comment_params
      params.required(:comment).permit :user_id, :post_id, :content
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.where(nil).order('created_at DESC')
  end

  def search
    @posts = Post.all
    if params[:caption]
      @posts = @posts.search_by_posts(params[:caption])

    else
      @posts = @posts
    end
  end

  def new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to posts_path
    else
      flash[:error] = @post.errors
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
    render 'posts/show'
  end

  def random
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:caption, :photo)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/', notice: 'Successfully logged in!'
    else
      flash.now.alert = "Incorrect email or password, try again."
      redirect_to '/login'
    end
  end

  def destroy
      session[:user_id] = nil
      redirect_to '/login', notice: "Logged out!"
    end

  def create_from_omniauth
      auth_hash = request.env["omniauth.auth"]
      authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

      # if: previously already logged in with OAuth
      if authentication.user
        user = authentication.user
        authentication.update_token(auth_hash)
        @next = root_url
        @notice = "Signed in!"
      # else: user logs in with OAuth for the first time
      else
        user = User.create_with_auth_and_hash(authentication, auth_hash)
        # you are expected to have a path that leads to a page for editing user details
        @next = edit_user_path(user)
        @notice = "User created. Please confirm or edit details"
      end

      sign_in(user)
      redirect_to @next, :notice => @notice
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Account created successfully!"
      redirect_to root_path

    else
      flash.now.alert = "Unable to register account. Please check details and try again."
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :bio, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", {post: @post} %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_content').val("");
console.log("create comment success");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", {post: @post} %>');
console.log("delete comment success");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
        Signed in as <%= current_user.first_name %> | <%= link_to "Logout", '/logout' %> | <%= link_to 'All Posts ', posts_path %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %> | <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_comment_form.html.erb
<%= form_for [post, Comment.new], :html => { :id => "comment-ajax"}, remote: true do |f| %>
<%#= form_with(model: [@post, @post.comments.build], local: true) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.text_field :content, placeholder: "Add a comment ...", autocomplete: :off %>
    <%= f.submit "Add comments" %>
<% end %>

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <br>
      <span>
        <strong>
          <%= link_to comment.user.first_name, user_path(comment.user) %></br>
        </strong>
      </span>
      <span><%= comment.content %></span>

      <% if comment.user == current_user %></br>
        <%= link_to "Delete comment", comment_path(comment),
          method: :delete, remote: true,
          data: { confirm: 'Are you sure?' } %></br>
      <% end %>
  <% end %>

app/views/posts/index.html.erb
<h1>Post index page</h1>

<%= link_to 'Create InstaPost', new_post_path%> |
<%= link_to 'Gif generator', random_path%>

<br>

<%= form_for :post, url: search_path, method: :get do |f| %>
  <%= f.text_field :caption, list: "list", placeholder: "search field", name: "caption" %><br/>
  <datalist id="list" ></datalist>
  <%= f.submit "Search" %>
<% end %>

<br>

<% @posts.each do |p| %>

  <%= p.user.first_name %></br>
  <%= image_tag(p.photo.thumb.url || "/asdkubakdjb") %></br>
  <%= p.caption %></br>
  <%= time_ago_in_words(p.created_at).upcase + " AGO" %></br>

<%= link_to 'Show ', post_path(p.id)%></br>

<br>

<%end%>

app/views/posts/new.html.erb
<h1>Create post page</h1>


<%= form_with scope: :post, url: posts_path, local: true do |form| %>

    <%= form.label :caption %>
    <%= form.text_field :caption, hide_label: true, placeholder: "Add a caption" %>

  <br>


  <%= form.label :Instaclone_photo %>
  <%= form.label :photo do %>
  <%= form.file_field :photo %>
  <%= form.hidden_field :photo_cache %>
 <% end %>

 <br>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/random.html.erb
<h2>Gif Generator</h2>

  <form id="query-form">
    <input id="query" type="text"/>
    <input type="submit" value="Generator"/>
  </form>

<br>

  <ul id="list-data" ></ul>

app/views/posts/search.html.erb
<h1>Search Results</h1>


<% @posts.each do |p| %>

  <%= p.user.first_name %></br>
  <%= image_tag(p.photo.thumb.url || "/asdkubakdjb") %></br>
  <%= p.caption %></br>
  <%= time_ago_in_words(p.created_at).upcase + " AGO" %></br>

<%= link_to 'Show ', post_path(p.id)%></br>

<%end%>

app/views/posts/show.html.erb
<h1>Show post page</h1>

<%= link_to 'Create InstaPost', new_post_path%>

<br>

<%= @post.user.first_name %></br>
<%= @post.caption %></br>
<%= time_ago_in_words(@post.created_at).upcase + " AGO" %></br>
<%= image_tag( @post.photo.thumb.url) %></br>

<% if @post.is_belongs_to? current_user %>
  <%= link_to '[Delete]', post_path(@post.id),
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
<%end%>
    <br>
    <br>

    <!-- load comments -->

 <div id="comment-post-<%= @post.id.to_s %>">
    <strong>Comments</strong>
      <%= render 'comment_list', {post: @post} %>
</div>

    <br>
    <br>

  <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
    <strong>Add a comment:</strong>
      <%= render 'comment_form', {post: @post} %>
  </div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for :user, url: '/users' do |f| %>
  <%= f.text_field :first_name, placeholder: "First name" %>
  <%= f.text_field :last_name, placeholder: "Last name" %>
  <%= f.email_field :email, placeholder: "Email" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
  <%= f.submit "Sign up" %>
<% end %>

app/views/welcome/index.html.erb
<h1>InstaClone</h1>